### ISSUE TITLE
Unable to connect to jgroup cluster using AWS_PING 

### ISSUE THREAD

**Issue by vishalkumkar** [meltmedia/jgroups-aws#11]
Hi, 

We are working on an application that requires AWS Auto Discovery of the nodes. We have the setup using jgroups ready.

We have tested by running the same application in AWS EC2 with preconfigured IP addresses and Cluster is getting built.

This is our AWS_PING line in the TCP.xml. We are using TCP unicast for communication.
 <com.meltmedia.jgroups.aws.AWS_PING timeout="3000" port_number="7900"  
    filters="InstanceType=t2.micro;KeyName=XXXXXXXX" access_key="XXXXXXXXX" secret_key="XXXXXXXXXXXXXXX"/>
      
The version of jgroups aws getting used is **1.3.1 **. Jgroups version is **3.6.8.Final**

We are using IPV4 stack, All Traffic is enabled on Ec2 instances and ec2-describe* command too works which gives details of other EC2 instances.

----------------------------------------------------------------------------------------------------------------------------------
But, when we use AWS_PING Protocol, we get an exception saying:
--------------------------------------------------------------------------------------------------------------------------------------------
**22-Apr-2016 00:07:16.766 WARNING [localhost-startStop-1] org.jgroups.stack.Confi                                                                                        gurator.resolveAndAssignField JGRP000014: BasicTCP.use_send_queues has been depr                                                                                        ecated: will be removed in 4.0
22-Apr-2016 00:07:16.777 WARNING [localhost-startStop-1] org.jgroups.stack.Confi                                                                                        gurator.resolveAndAssignField JGRP000014: TP.loopback has been deprecated: enabl                                                                                        ed by default
22-Apr-2016 00:07:16.777 WARNING [localhost-startStop-1] org.jgroups.stack.Confi                                                                                        gurator.resolveAndAssignField JGRP000014: TP.discard_incompatible_packets has be                                                                                        en deprecated: incompatible packets are discarded anyway
22-Apr-2016 00:07:16.778 WARNING [localhost-startStop-1] org.jgroups.stack.Confi                                                                                        gurator.resolveAndAssignField JGRP000014: TP.enable_bundling has been deprecated                                                                                        : will be ignored as bundling is on by default
22-Apr-2016 00:07:16.786 WARNING [localhost-startStop-1] org.jgroups.stack.Confi                                                                                        gurator.resolveAndAssignField JGRP000014: Discovery.timeout has been deprecated:                                                                                         GMS.join_timeout should be used instead
22-Apr-2016 00:07:17.628 INFO [localhost-startStop-1] org.jgroups.protocols.UFC.                                                                                        init UFC is not needed (and can be removed) as we're running on a TCP transport

-------------------------------------------------------------------
GMS: address=ip-172-31-54-146-23940, cluster=usermap, physical address=172.31.54                                                                                        .146:7900
-------------------------------------------------------------------
java.lang.Exception: connecting to channel "usermap" failed
        at org.jgroups.JChannel._connect(JChannel.java:570)
        at org.jgroups.JChannel.connect(JChannel.java:294)
        at org.jgroups.JChannel.connect(JChannel.java:279)
        at org.jgroups.blocks.ReplCache.start(ReplCache.java:278)
        at com.cloud.jgroups.NodeInitializer.contextInitialized(NodeInitializer.                                                                                        java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContex                                                                                        t.java:4811)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContex                                                                                        t.java:5251)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase                                                                                        .java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:70                                                                                        1)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:                                                                                        1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:51                                                                                        1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                        java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                        .java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AbstractMethodError: org.jgroups.protocols.Discovery.findMe                                                                                        mbers(Ljava/util/List;ZLorg/jgroups/util/Responses;)V
        at org.jgroups.protocols.Discovery.findMembers(Discovery.java:244)
        at org.jgroups.protocols.Discovery.down(Discovery.java:385)
        at org.jgroups.protocols.MERGE3.down(MERGE3.java:254)
        at org.jgroups.protocols.FD_SOCK.down(FD_SOCK.java:371)
        at org.jgroups.protocols.FD.down(FD.java:318)
        at org.jgroups.protocols.VERIFY_SUSPECT.down(VERIFY_SUSPECT.java:92)
        at org.jgroups.protocols.BARRIER.down(BARRIER.java:132)
        at org.jgroups.protocols.pbcast.NAKACK2.down(NAKACK2.java:582)
        at org.jgroups.protocols.UNICAST3.down(UNICAST3.java:669)
        at org.jgroups.protocols.pbcast.STABLE.down(STABLE.java:347)
        at org.jgroups.protocols.pbcast.ClientGmsImpl.joinInternal(ClientGmsImpl                                                                                        .java:76)
        at org.jgroups.protocols.pbcast.ClientGmsImpl.join(ClientGmsImpl.java:41                                                                                        )
        at org.jgroups.protocols.pbcast.GMS.down(GMS.java:1085)
        at org.jgroups.protocols.FlowControl.down(FlowControl.java:351)
        at org.jgroups.protocols.FlowControl.down(FlowControl.java:351)
        at org.jgroups.protocols.FRAG2.down(FRAG2.java:136)
        at org.jgroups.protocols.pbcast.STATE_TRANSFER.down(STATE_TRANSFER.java:                                                                                        202)
        at org.jgroups.stack.ProtocolStack.down(ProtocolStack.java:1039)
        at org.jgroups.JChannel.down(JChannel.java:790)
        at org.jgroups.JChannel._connect(JChannel.java:564)
        ... 17 more
**

**Comment by vishalkumkar** [comment]
Hi,
We were able to resolve issue by upgrading aws jgroups jar version to 1.4.0.

Thanks,
Vishal.
