### ISSUE TITLE
Would a failure in AWS_PING.findMembers() be terminal for a node?

### ISSUE THREAD

**Issue by paulhoadley** [meltmedia/jgroups-aws#22]
Hello,

This isn't really a code _issue,_ just a question about it, and I'm not sure there's a more appropriate forum. Also, I'm still using 1.4.2, though the question should be general enough to be applicable to the latest release.

I have a web application running on several instances. One of them saw this stack trace a few days ago:

    Aug 26, 2018 11:11:19 AM org.jgroups.protocols.MERGE2$FindSubgroupsTask findAndNotify
    SEVERE: JGRP000242: FindSubgroupsTask failed
    com.amazonaws.services.ec2.model.AmazonEC2Exception: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code:
     AuthFailure; Request ID: c172da23-4bbb-44b2-9531-bb55b607d5d3)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:16126)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:16102)
        at com.amazonaws.services.ec2.AmazonEC2Client.executeDescribeInstances(AmazonEC2Client.java:7846)
        at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:7821)
        at com.meltmedia.jgroups.aws.AWS_PING.getInstanceTags(AWS_PING.java:519)
        at com.meltmedia.jgroups.aws.AWS_PING.getPrivateIpAddresses(AWS_PING.java:378)
        at com.meltmedia.jgroups.aws.AWS_PING.findMembers(AWS_PING.java:328)
        at org.jgroups.protocols.Discovery.findMembers(Discovery.java:244)
        at org.jgroups.protocols.Discovery.down(Discovery.java:388)
        at org.jgroups.protocols.MERGE2$FindSubgroupsTask.fetchViews(MERGE2.java:446)
        at org.jgroups.protocols.MERGE2$FindSubgroupsTask._findAndNotify(MERGE2.java:374)
        at org.jgroups.protocols.MERGE2$FindSubgroupsTask.findAndNotify(MERGE2.java:359)
        at org.jgroups.protocols.MERGE2$FindSubgroupsTask$1.run(MERGE2.java:330)
        at org.jgroups.util.TimeScheduler2$RecurringTask.run(TimeScheduler2.java:563)
        at org.jgroups.util.TimeScheduler2$MyTask.run(TimeScheduler2.java:495)
        at org.jgroups.util.TimeScheduler2$Entry.execute(TimeScheduler2.java:400)
        at org.jgroups.util.TimeScheduler2$1.run(TimeScheduler2.java:260)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

My question is quite simple: was that a _terminal_ failure for that node, or would JGroups have tried again and presumably re-joined the cluster? (The "authentication failure" was due to something transient AWS-side—the credentials in use are fine.)

(I don't have logging for JGroups turned up high enough to see what happened next, _but_ there was some application-level weirdness that might be explained if JGroups had died on that node.)

**Comment by ctrimble** [comment]
I would not think it died on that node, but I could be wrong.  We would probably need to dig around in JGroups code for an authoritative answer.  You could ask the JGroups list if `Discovery.findMembers` will get called again after it throws an exception.

I am happy to help get a PR released if we need to change the error handling in this method.

**Comment by ctrimble** [comment]
The entry point from JGroups is here: https://github.com/belaban/JGroups/blob/master/src/org/jgroups/protocols/Discovery.java#L200

**Comment by paulhoadley** [comment]
> I would not think it died on that node, but I could be wrong.

Thanks for the reply Christian. I'll follow this up in JGroups.
